[workspace]
members = [
    "crates/common",
    "crates/vm",
    "crates/verifier",
    "crates/assembler",
    "nolang-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
